-- =============================================================
-- Peptide Inventory App - Complete Schema
-- Tables: 57
-- Total columns: 569
-- Generated by parse_schema.py
-- =============================================================

-- Table: admin_ai_logs (9 columns)
CREATE TABLE IF NOT EXISTS admin_ai_logs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid,
    session_ts timestamptz DEFAULT now(),
    tool_name text,
    tool_args jsonb,
    tool_result text,
    error text,
    duration_ms integer,
    created_at timestamptz DEFAULT now()
);

-- Table: admin_chat_messages (5 columns)
CREATE TABLE IF NOT EXISTS admin_chat_messages (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    role text NOT NULL,
    content text NOT NULL,
    created_at timestamptz DEFAULT now()
);

-- Table: ai_conversations (5 columns)
CREATE TABLE IF NOT EXISTS ai_conversations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    title text DEFAULT 'Peptide AI'::text,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- Table: ai_documents (10 columns)
CREATE TABLE IF NOT EXISTS ai_documents (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    file_name text NOT NULL,
    file_type text NOT NULL,
    storage_path text NOT NULL,
    status text DEFAULT 'pending'::text,
    extracted_text text,
    summary text,
    chunk_count integer DEFAULT 0,
    created_at timestamptz DEFAULT now()
);

-- Table: ai_health_profiles (10 columns)
CREATE TABLE IF NOT EXISTS ai_health_profiles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    conditions jsonb DEFAULT '[]'::jsonb,
    goals jsonb DEFAULT '[]'::jsonb,
    medications jsonb DEFAULT '[]'::jsonb,
    allergies jsonb DEFAULT '[]'::jsonb,
    supplements jsonb DEFAULT '[]'::jsonb,
    lab_values jsonb DEFAULT '{}'::jsonb,
    notes text DEFAULT ''::text,
    updated_at timestamptz DEFAULT now()
);

-- Table: ai_learned_insights (9 columns)
CREATE TABLE IF NOT EXISTS ai_learned_insights (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    category text NOT NULL,
    title text NOT NULL,
    content text NOT NULL,
    source text,
    source_url text,
    relevance_score double precision DEFAULT 1.0,
    created_at timestamptz DEFAULT now()
);

-- Table: ai_messages (6 columns)
CREATE TABLE IF NOT EXISTS ai_messages (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    conversation_id uuid NOT NULL,
    role text NOT NULL,
    content text NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb,
    created_at timestamptz DEFAULT now()
);

-- Table: audit_log (9 columns)
CREATE TABLE IF NOT EXISTS audit_log (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid,
    user_id uuid,
    table_name text NOT NULL,
    record_id uuid NOT NULL,
    action text NOT NULL,
    old_data jsonb,
    new_data jsonb,
    created_at timestamptz DEFAULT now() NOT NULL
);

-- Table: automation_modules (8 columns)
CREATE TABLE IF NOT EXISTS automation_modules (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    module_type text NOT NULL,
    enabled boolean DEFAULT true,
    config jsonb DEFAULT '{}'::jsonb,
    last_run_at timestamptz,
    run_count integer DEFAULT 0,
    created_at timestamptz DEFAULT now()
);

-- Table: body_composition_logs (13 columns)
CREATE TABLE IF NOT EXISTS body_composition_logs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid,
    date date DEFAULT CURRENT_DATE NOT NULL,
    weight numeric,
    body_fat_percentage numeric,
    muscle_mass numeric,
    visceral_fat numeric,
    water_percentage numeric,
    bmi numeric,
    bmr numeric,
    notes text,
    created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table: bottles (9 columns)
CREATE TABLE IF NOT EXISTS bottles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    lot_id uuid NOT NULL,
    uid text NOT NULL,
    status bottle_status DEFAULT 'in_stock'::bottle_status NOT NULL,
    location text,
    notes text,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL
);

-- Table: client_daily_logs (10 columns)
CREATE TABLE IF NOT EXISTS client_daily_logs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    contact_id uuid,
    log_date date NOT NULL,
    weight_lbs numeric,
    body_fat_pct numeric,
    water_intake_oz numeric,
    notes text,
    side_effects text[],
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- Table: client_inventory (23 columns)
CREATE TABLE IF NOT EXISTS client_inventory (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    contact_id uuid,
    peptide_id uuid,
    batch_number text,
    vial_size_mg numeric NOT NULL,
    water_added_ml numeric,
    concentration_mg_ml numeric,
    reconstituted_at timestamptz,
    expires_at timestamptz,
    current_quantity_mg numeric NOT NULL,
    status text DEFAULT 'active'::text,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    movement_id uuid,
    initial_quantity_mg numeric,
    protocol_item_id uuid,
    dose_amount_mg numeric,
    dose_days text[],
    in_fridge boolean DEFAULT false,
    dose_frequency text,
    dose_interval integer,
    dose_off_days integer,
    dose_time_of_day text
);

-- Table: client_requests (17 columns)
CREATE TABLE IF NOT EXISTS client_requests (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    user_id uuid NOT NULL,
    type request_type DEFAULT 'product_request'::request_type NOT NULL,
    status request_status DEFAULT 'pending'::request_status NOT NULL,
    subject text,
    message text,
    peptide_id uuid,
    requested_quantity integer DEFAULT 1,
    admin_notes text,
    fulfilled_movement_id uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    attachments jsonb DEFAULT '[]'::jsonb,
    admin_attachments jsonb DEFAULT '[]'::jsonb,
    context_type text,
    context_id uuid
);

-- Table: client_supplements (6 columns)
CREATE TABLE IF NOT EXISTS client_supplements (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    contact_id uuid,
    name text NOT NULL,
    dosage text,
    frequency text,
    created_at timestamptz DEFAULT now()
);

-- Table: commissions (8 columns)
CREATE TABLE IF NOT EXISTS commissions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    sale_id uuid,
    partner_id uuid,
    amount numeric NOT NULL,
    commission_rate numeric,
    type text,
    status text DEFAULT 'pending'::text,
    created_at timestamptz DEFAULT now()
);

-- Table: contact_notes (6 columns)
CREATE TABLE IF NOT EXISTS contact_notes (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    contact_id uuid NOT NULL,
    content text NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    created_by uuid,
    org_id uuid NOT NULL
);

-- Table: contacts (21 columns)
CREATE TABLE IF NOT EXISTS contacts (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    name text NOT NULL,
    email text,
    phone text,
    type contact_type DEFAULT 'customer'::contact_type NOT NULL,
    company text,
    notes text,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    linked_user_id uuid,
    tier text DEFAULT 'public'::text,
    invite_link text,
    assigned_rep_id uuid,
    claim_token uuid DEFAULT gen_random_uuid(),
    claim_token_expires_at timestamptz DEFAULT (now() + '7 days'::interval),
    address text,
    household_id uuid,
    household_role text,
    woo_customer_id bigint,
    source text DEFAULT 'manual'::text NOT NULL
);

-- Table: daily_hours (8 columns)
CREATE TABLE IF NOT EXISTS daily_hours (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    org_id uuid NOT NULL,
    work_date date NOT NULL,
    hours numeric NOT NULL,
    notes text,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- Table: daily_macro_goals (9 columns)
CREATE TABLE IF NOT EXISTS daily_macro_goals (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid,
    calories_target integer DEFAULT 2000,
    protein_target integer DEFAULT 150,
    carbs_target integer DEFAULT 200,
    fat_target integer DEFAULT 65,
    created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
    water_goal_oz integer DEFAULT 64
);

-- Table: discussion_messages (7 columns)
CREATE TABLE IF NOT EXISTS discussion_messages (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    topic_id uuid NOT NULL,
    user_id uuid NOT NULL,
    content text NOT NULL,
    parent_id uuid,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- Table: discussion_topics (9 columns)
CREATE TABLE IF NOT EXISTS discussion_topics (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    title text NOT NULL,
    content text,
    theme_id uuid,
    user_id uuid NOT NULL,
    is_pinned boolean DEFAULT false,
    message_count integer DEFAULT 0,
    last_activity_at timestamptz DEFAULT now(),
    created_at timestamptz DEFAULT now()
);

-- Table: embeddings (4 columns)
CREATE TABLE IF NOT EXISTS embeddings (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    content text,
    metadata jsonb,
    embedding vector
);

-- Table: expenses (11 columns)
CREATE TABLE IF NOT EXISTS expenses (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
    date date DEFAULT CURRENT_DATE NOT NULL,
    category text NOT NULL,
    amount numeric NOT NULL,
    description text,
    recipient text,
    payment_method text,
    status text DEFAULT 'paid'::text,
    related_order_id uuid,
    related_sales_order_id uuid
);

-- Table: favorite_foods (12 columns)
CREATE TABLE IF NOT EXISTS favorite_foods (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    name text NOT NULL,
    calories numeric DEFAULT 0 NOT NULL,
    protein numeric DEFAULT 0 NOT NULL,
    carbs numeric DEFAULT 0 NOT NULL,
    fat numeric DEFAULT 0 NOT NULL,
    quantity text DEFAULT '1 serving'::text,
    created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL,
    is_template boolean DEFAULT false,
    template_name varchar(255),
    meal_type varchar(50)
);

-- Table: lots (14 columns)
CREATE TABLE IF NOT EXISTS lots (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    peptide_id uuid NOT NULL,
    lot_number text NOT NULL,
    quantity_received integer NOT NULL,
    cost_per_unit numeric NOT NULL,
    received_date date DEFAULT CURRENT_DATE NOT NULL,
    expiry_date date,
    notes text,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    payment_status text DEFAULT 'unpaid'::text,
    payment_date date,
    payment_method text
);

-- Table: meal_logs (9 columns)
CREATE TABLE IF NOT EXISTS meal_logs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid,
    image_url text,
    foods jsonb DEFAULT '[]'::jsonb,
    total_calories numeric DEFAULT 0,
    total_protein numeric DEFAULT 0,
    total_carbs numeric DEFAULT 0,
    total_fat numeric DEFAULT 0,
    created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table: movement_items (6 columns)
CREATE TABLE IF NOT EXISTS movement_items (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    movement_id uuid NOT NULL,
    bottle_id uuid,
    price_at_sale numeric,
    created_at timestamptz DEFAULT now() NOT NULL,
    description text
);

-- Table: movements (15 columns)
CREATE TABLE IF NOT EXISTS movements (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    type movement_type NOT NULL,
    contact_id uuid,
    movement_date date DEFAULT CURRENT_DATE NOT NULL,
    notes text,
    created_by uuid,
    created_at timestamptz DEFAULT now() NOT NULL,
    payment_status text DEFAULT 'unpaid'::text,
    amount_paid numeric DEFAULT 0,
    payment_method text,
    payment_date timestamptz,
    status text DEFAULT 'active'::text,
    discount_percent numeric DEFAULT 0,
    discount_amount numeric DEFAULT 0
);

-- Table: newsletter_subscribers (4 columns)
CREATE TABLE IF NOT EXISTS newsletter_subscribers (
    id bigint NOT NULL,
    email text NOT NULL,
    subscribed_at timestamptz DEFAULT now() NOT NULL,
    source text DEFAULT 'website_footer'::text
);

-- Table: notifications (8 columns)
CREATE TABLE IF NOT EXISTS notifications (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid,
    title text NOT NULL,
    message text NOT NULL,
    link text,
    type text DEFAULT 'info'::text,
    is_read boolean DEFAULT false,
    created_at timestamptz DEFAULT now()
);

-- Table: orders (16 columns)
CREATE TABLE IF NOT EXISTS orders (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    peptide_id uuid NOT NULL,
    quantity_ordered integer NOT NULL,
    estimated_cost_per_unit numeric,
    order_date date DEFAULT CURRENT_DATE NOT NULL,
    expected_arrival_date date,
    supplier text,
    tracking_number text,
    notes text,
    status text DEFAULT 'pending'::text NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    payment_status text DEFAULT 'unpaid'::text,
    amount_paid numeric DEFAULT 0.00,
    order_group_id text
);

-- Table: organizations (4 columns)
CREATE TABLE IF NOT EXISTS organizations (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL
);

-- Table: partner_chat_messages (6 columns)
CREATE TABLE IF NOT EXISTS partner_chat_messages (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    user_id uuid NOT NULL,
    role text NOT NULL,
    content text NOT NULL,
    created_at timestamptz DEFAULT now()
);

-- Table: partner_suggestions (8 columns)
CREATE TABLE IF NOT EXISTS partner_suggestions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    partner_id uuid NOT NULL,
    suggestion_text text NOT NULL,
    category text DEFAULT 'feature'::text NOT NULL,
    status text DEFAULT 'new'::text NOT NULL,
    admin_notes text,
    created_at timestamptz DEFAULT now()
);

-- Table: payment_email_queue (20 columns)
CREATE TABLE IF NOT EXISTS payment_email_queue (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    gmail_message_id text NOT NULL,
    sender_name text,
    amount numeric NOT NULL,
    payment_method text NOT NULL,
    email_subject text,
    email_snippet text,
    email_date timestamptz,
    matched_contact_id uuid,
    matched_movement_id uuid,
    status text DEFAULT 'pending'::text NOT NULL,
    confidence text DEFAULT 'low'::text NOT NULL,
    auto_posted_at timestamptz,
    reviewed_by uuid,
    reviewed_at timestamptz,
    notes text,
    created_at timestamptz DEFAULT now(),
    ai_suggested_contact_id uuid,
    ai_reasoning text
);

-- Table: peptide_pricing (7 columns)
CREATE TABLE IF NOT EXISTS peptide_pricing (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    peptide_id uuid NOT NULL,
    tier price_tier NOT NULL,
    price numeric NOT NULL,
    effective_from date DEFAULT CURRENT_DATE NOT NULL,
    effective_to date,
    created_at timestamptz DEFAULT now() NOT NULL
);

-- Table: peptide_suggested_supplements (5 columns)
CREATE TABLE IF NOT EXISTS peptide_suggested_supplements (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    peptide_id uuid NOT NULL,
    supplement_id uuid NOT NULL,
    reasoning text,
    created_at timestamptz DEFAULT now()
);

-- Table: peptides (16 columns)
CREATE TABLE IF NOT EXISTS peptides (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    name text NOT NULL,
    description text,
    sku text,
    active boolean DEFAULT true NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    retail_price numeric DEFAULT 0,
    default_dose_amount numeric,
    default_dose_unit text DEFAULT 'mcg'::text,
    default_frequency text DEFAULT 'daily'::text,
    default_timing text,
    default_concentration_mg_ml numeric,
    reconstitution_notes text,
    visible_to_user_ids uuid[]
);

-- Table: profiles (16 columns)
CREATE TABLE IF NOT EXISTS profiles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    org_id uuid,
    full_name text,
    email text,
    created_at timestamptz DEFAULT now() NOT NULL,
    updated_at timestamptz DEFAULT now() NOT NULL,
    role text DEFAULT 'admin'::text,
    commission_rate numeric DEFAULT 0.00,
    credit_balance numeric DEFAULT 0.00,
    parent_partner_id uuid,
    partner_tier text DEFAULT 'standard'::text,
    price_multiplier numeric DEFAULT 1.0,
    parent_rep_id uuid,
    pricing_mode text DEFAULT 'percentage'::text,
    cost_plus_markup numeric DEFAULT 0
);

-- Table: protocol_feedback (10 columns)
CREATE TABLE IF NOT EXISTS protocol_feedback (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    protocol_id uuid,
    user_id uuid,
    rating smallint,
    comment text,
    created_at timestamptz DEFAULT now(),
    admin_response text,
    response_link text,
    response_at timestamptz,
    is_read_by_client boolean DEFAULT false
);

-- Table: protocol_items (12 columns)
CREATE TABLE IF NOT EXISTS protocol_items (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    protocol_id uuid NOT NULL,
    peptide_id uuid NOT NULL,
    dosage_amount numeric NOT NULL,
    dosage_unit text DEFAULT 'mcg'::text NOT NULL,
    frequency text NOT NULL,
    duration_weeks numeric NOT NULL,
    price_tier text DEFAULT 'retail'::text NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    duration_days integer,
    cost_multiplier numeric DEFAULT 1.0
);

-- Table: protocol_logs (7 columns)
CREATE TABLE IF NOT EXISTS protocol_logs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    protocol_item_id uuid NOT NULL,
    user_id uuid,
    taken_at timestamptz DEFAULT now(),
    status text DEFAULT 'taken'::text,
    notes text,
    created_at timestamptz DEFAULT now()
);

-- Table: protocol_supplements (7 columns)
CREATE TABLE IF NOT EXISTS protocol_supplements (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    protocol_id uuid NOT NULL,
    supplement_id uuid NOT NULL,
    dosage text,
    frequency text,
    notes text,
    created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table: protocols (7 columns)
CREATE TABLE IF NOT EXISTS protocols (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    contact_id uuid,
    name text NOT NULL,
    description text,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- Table: request_replies (7 columns)
CREATE TABLE IF NOT EXISTS request_replies (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    request_id uuid NOT NULL,
    user_id uuid NOT NULL,
    message text,
    attachments jsonb DEFAULT '[]'::jsonb,
    is_internal boolean DEFAULT false,
    created_at timestamptz DEFAULT now()
);

-- Table: resource_comments (5 columns)
CREATE TABLE IF NOT EXISTS resource_comments (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    resource_id uuid NOT NULL,
    user_id uuid NOT NULL,
    content text NOT NULL,
    created_at timestamptz DEFAULT now()
);

-- Table: resource_themes (6 columns)
CREATE TABLE IF NOT EXISTS resource_themes (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    description text,
    created_at timestamptz DEFAULT now(),
    icon text DEFAULT 'beaker'::text,
    color text DEFAULT '#10b981'::text
);

-- Table: resource_views (4 columns)
CREATE TABLE IF NOT EXISTS resource_views (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    resource_id uuid NOT NULL,
    user_id uuid,
    viewed_at timestamptz DEFAULT now()
);

-- Table: resources (16 columns)
CREATE TABLE IF NOT EXISTS resources (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    peptide_id uuid,
    title text NOT NULL,
    url text NOT NULL,
    type text,
    description text,
    created_at timestamptz DEFAULT now(),
    contact_id uuid,
    content text,
    link_button_text text DEFAULT 'Open'::text,
    theme_id uuid,
    thumbnail_url text,
    is_featured boolean DEFAULT false,
    view_count integer DEFAULT 0,
    duration_seconds integer,
    duration integer
);

-- Table: sales_order_items (6 columns)
CREATE TABLE IF NOT EXISTS sales_order_items (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    sales_order_id uuid NOT NULL,
    peptide_id uuid NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric NOT NULL,
    created_at timestamptz DEFAULT now()
);

-- Table: sales_orders (37 columns)
CREATE TABLE IF NOT EXISTS sales_orders (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    client_id uuid NOT NULL,
    rep_id uuid,
    status text DEFAULT 'draft'::text NOT NULL,
    total_amount numeric DEFAULT 0 NOT NULL,
    commission_amount numeric DEFAULT 0,
    payment_status text DEFAULT 'unpaid'::text NOT NULL,
    amount_paid numeric DEFAULT 0,
    payment_method text,
    payment_date timestamptz,
    shipping_address text,
    notes text,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    commission_status text DEFAULT 'pending'::text,
    psifi_session_id text,
    psifi_transaction_id text,
    psifi_status text DEFAULT 'none'::text,
    tracking_number text,
    carrier text,
    shipping_status text DEFAULT 'pending'::text,
    ship_date timestamptz,
    shipping_cost numeric DEFAULT 0,
    label_url text,
    shippo_shipment_id text,
    shippo_transaction_id text,
    shipping_error text,
    order_source text DEFAULT 'app'::text,
    woo_order_id bigint,
    woo_status text,
    woo_date_created timestamptz,
    woo_date_modified timestamptz,
    cogs_amount numeric DEFAULT 0,
    profit_amount numeric DEFAULT 0,
    merchant_fee numeric DEFAULT 0,
    delivery_method text DEFAULT 'ship'::text
);

-- Table: sender_aliases (7 columns)
CREATE TABLE IF NOT EXISTS sender_aliases (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    sender_name text NOT NULL,
    contact_id uuid NOT NULL,
    payment_method text,
    created_by uuid,
    created_at timestamptz DEFAULT now()
);

-- Table: supplements (7 columns)
CREATE TABLE IF NOT EXISTS supplements (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    description text,
    image_url text,
    purchase_link text,
    default_dosage text,
    created_at timestamptz DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Table: tenant_config (23 columns)
CREATE TABLE IF NOT EXISTS tenant_config (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    org_id uuid NOT NULL,
    brand_name text DEFAULT 'Peptide AI'::text NOT NULL,
    admin_brand_name text DEFAULT 'Peptide Admin'::text NOT NULL,
    support_email text DEFAULT ''::text,
    app_url text DEFAULT ''::text,
    logo_url text DEFAULT ''::text,
    primary_color text DEFAULT '#7c3aed'::text,
    ship_from_name text DEFAULT ''::text,
    ship_from_street text DEFAULT ''::text,
    ship_from_city text DEFAULT ''::text,
    ship_from_state text DEFAULT ''::text,
    ship_from_zip text DEFAULT ''::text,
    ship_from_country text DEFAULT 'US'::text,
    ship_from_phone text DEFAULT ''::text,
    ship_from_email text DEFAULT ''::text,
    zelle_email text DEFAULT ''::text,
    venmo_handle text DEFAULT ''::text,
    cashapp_handle text DEFAULT ''::text,
    ai_system_prompt_override text,
    session_timeout_minutes integer DEFAULT 60,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- Table: user_roles (5 columns)
CREATE TABLE IF NOT EXISTS user_roles (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    org_id uuid NOT NULL,
    role app_role DEFAULT 'viewer'::app_role NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL
);

-- Table: water_logs (5 columns)
CREATE TABLE IF NOT EXISTS water_logs (
    id uuid DEFAULT uuid_generate_v4() NOT NULL,
    user_id uuid NOT NULL,
    amount_oz integer NOT NULL,
    logged_at timestamptz DEFAULT now(),
    created_at timestamptz DEFAULT now()
);

